name: LTM_IXI_BraTS
target_size: &target_size !!python/tuple [128, 128]
train_batch_size: &tbatch_size 24
downstream_batch_size: &dbatch_size 1
num_workers: &num_workers 8
checkpoint_path: &checkpoint_path ./weights/IXI_BraTS/ltm/

experiment:
  name: IXI_BraTS_AnomalyDetection
  task: train
  weights:

device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:

#
# Model - LTM (Latent Transformer Model)
# Note: LTM requires pre-trained VQ-VAE. First train VQ-VAE, then train LTM.
#
model:
  module_name: model_zoo.transformers
  class_name: DecoderOnlyTransformer
  params:
    num_tokens: 17
    max_seq_len: 1024
    attn_layers_dim: 128
    attn_layers_depth: 16
    attn_layers_heads: 16

trainer:
  module_name: projects.24_normative_eval.trainers.LTM_Trainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    batch_size: *tbatch_size
    nr_epochs: 1500
    patience: 1500
    val_interval: 50
    vqvae_path: './weights/IXI_BraTS/vqvae/2025_12_17_22_57_54_886220/best_model.pt'
    loss:
      module_name: optim.losses.ln_losses
      class_name: L1
      params:
    optimizer_params:
      lr: 5.0e-4
  data_loader:
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.brain_loader
          class_name: BrainLoader
        data_dir:
          train:
            - './data/IXI_BraTS/splits/ixi_train.csv'
          val:
            - './data/IXI_BraTS/splits/ixi_val.csv'
          test:
            - './data/IXI_BraTS/splits/ixi_val.csv'
        target_size: *target_size
        batch_size: *tbatch_size
        num_workers: *num_workers

downstream_tasks:
  brats_detection:
    module_name: projects.24_normative_eval.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    params:
      task: 'detection'
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          dataset_module:
            module_name: data.loaders.brain_loader
            class_name: BrainLoader
          data_dir:
            test:
              - './data/IXI_BraTS/splits/brats_test.csv'
            mask:
              - './data/IXI_BraTS/splits/brats_test_masks.csv'
            neg:
              - './data/IXI_BraTS/splits/brats_test_neg.csv'
