name: AutoDDPM_MOOD_IXI_BraTS_Eval
target_size: &target_size !!python/tuple [128, 128]
train_batch_size: &tbatch_size 16
downstream_batch_size: &dbatch_size 32
num_workers: &num_workers 8
checkpoint_path: &checkpoint_path ./weights/MOOD_IXI/autoddpm/

experiment:
  name: MOOD_IXI_BraTS_AnomalyDetection
  task: test
  weights: './weights/MOOD_IXI/autoddpm/2026_03_10_19_00_45_333222/best_model.pt'

device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:

model:
  module_name: model_zoo.ddpm
  class_name: DDPM
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels:
      - 128
      - 256
      - 256
    attention_levels:
      - False
      - True
      - True
    num_res_blocks: 1
    num_head_channels: 256
    train_scheduler: ddpm
    inference_scheduler: ddpm
    inference_steps: 1000
    noise_level_recon: 300
    noise_level_inpaint: 50
    noise_type: gaussian
    prediction_type: epsilon
    resample_steps: 3
    masking_threshold: 0.1
    inference_type: 'auto'
    threshold_low: 1
    threshold_high: 10000
    image_path: './projects/24_normative_eval/images/autoddpm_mood_ixi'

trainer:
  module_name: projects.24_normative_eval.trainers.AnoTrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    batch_size: *tbatch_size
    nr_epochs: 1500
    val_interval: 50
    patience: 500
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    optimizer_params:
      lr: 1.0e-4
  data_loader:
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        target_size: *target_size
        batch_size: *tbatch_size
        num_workers: *num_workers
        dataset_module:
          module_name: data.loaders.brain_nifti_loader
          class_name: BrainNiftiLoader
        data_dir:
          train:
            - './data/MOOD_IXI_3D/splits/mood_ixi_train.csv'
          val:
            - './data/MOOD_IXI_3D/splits/mood_ixi_val.csv'
          test:
            - './data/MOOD_IXI_3D/splits/mood_ixi_val.csv'

downstream_tasks:
  brats_detection:
    module_name: projects.24_normative_eval.DownstreamEvaluatorAtlas
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          num_workers: *num_workers
          dataset_module:
            module_name: data.loaders.brain_loader
            class_name: BrainLoader
      datasets:
        BraTS_Combined:
          data_dir:
            test:
              - './data/IXI_BraTS/splits/brats_healthy_combined_test.csv'
          label_dir:
            test:
              - './data/IXI_BraTS/splits/brats_healthy_combined_test_masks.csv'
          mask_dir:
            test:
              - './data/IXI_BraTS/splits/brats_test_neg.csv'
